### ISSUE TITLE
User_Data provide only one user data no matter who publish the new Post.

### ISSUE THREAD

**Issue by movibeast** [vanokhin/shortcodes-ultimate#107]
**Describe the bug**
Hi, so here is the thing. When a user of my team try to publish the new post (as a author) it shows the name of me. Even he is uploading still it shows my name.
**To Reproduce**
1. Go to 'new post'
2. Add the shortcode 'or user data'
3. Scroll down to 'make it show the name'
4. and when published, it shows My name.

**Expected behavior**
It should show the name of the Author whos post it is!

**Screenshots**
I have attached the images for your reference.
![image](https://user-images.githubusercontent.com/34957562/77960500-0931c780-72f6-11ea-9d2a-014026087d1b.png)
![image](https://user-images.githubusercontent.com/34957562/77960450-f3240700-72f5-11ea-8397-1bfcecca1819.png)

Between I am adding the shortcode below
`[su_row][su_column size="1/2" center="no" class=""] Uploaded by : [su_user field="display_name"] [/su_column]`

**Additional context**
Nothing

**Comment by vanokhin** [comment]
Hi @movibeast,

this is expected behavior. The User shortcode is about displaying user data, not post data.

`[su_user field="display_name"]` – uses current user ID, not post author, but current authorized user.

You can add one more shortcode to display post author:

```
[su_user field="display_name" user_id="{su_post field=post_author post_type=post}"]
```
