### ISSUE TITLE
Using WebP plugins with Image Carousel

### ISSUE THREAD

**Issue by andryushchenko** [vanokhin/shortcodes-ultimate#110]
I'm using WebP Express plugin in CDN-friendly (modify HTML) mode - <img> tags are replaced width <picture> with both original (jpeg or png) and webp source.
It works well with images thumbnails in Image Carousel. Is it possible to use this in maximized lightbox?

**Comment by vanokhin** [comment]
Hi Anton,

Image Carousel displays images only using WordPress's functions (nothing custom). Lightbox image URL is retrieved using `wp_get_attachment_image_src()`. [The code](https://github.com/vanokhin/shortcodes-ultimate/blob/master/includes/functions-galleries.php#L296).

I think it's better to ask the developer of the WebP Express plugin to add support for that function. According to the function [source code](https://core.trac.wordpress.org/browser/tags/5.4/src/wp-includes/media.php#L952), it can be filtered.
