### ISSUE TITLE
Custom gallery using taxonomy does not show links using custom link option

### ISSUE THREAD

**Issue by tomasalmeida** [vanokhin/shortcodes-ultimate#111]
**Describe the bug**
Custom gallery using taxonomy (and the sub-option tag) does not show links using custom link option. Image has the su_slide_link set.

**To Reproduce**
1. Go to SU option and create a new short code Custom Gallery
2. Select image source: taxonomy
3. Select taxonomy "tag" 
4. Select one tag
5. In link to option, select custom link
6. Do not change other options
7. Click OK to create short code.
8. Go to preview
9. Images do not have the link set on su custom link in media editor.

**Expected behavior**
Images have the link set on su custom link in media editor.

**Screenshots**
- not relevant

**Active plugins (please post a list of active plugins):**
- tested in a vanilla wordpress and faced the same issue

**System (please complete the following information):**
- not relevant

**Additional context**
only reproducible with gallery with taxonomy. Selecting one by one the images, it works.

**Comment by vanokhin** [comment]
Hi @tomasalmeida,

please post here your shortcode and screenshot of the page where you editing custom link (the whole browser window with URL).

**Comment by tomasalmeida** [comment]
Hi @vanokhin, here the shortcode:

`[su_custom_gallery source="taxonomy: post_tag/123" limit="40" link="custom" target="blank" width="240" height="200" title="always"]`

and the screenshost (sensitive data was covered)
![Captura](https://user-images.githubusercontent.com/1017600/81502246-1ff81080-92dd-11ea-8ec4-405ff0a1ac9f.png)

thanks

**Comment by vanokhin** [comment]
Hi @tomasalmeida,

I've fixed the issue in 0db72039e63c72a86a3f0f439b8004f3855efe83.

Thank you for the report.

**Comment by tomasalmeida** [comment]
Thank you for fixing it so fast! Thanks!
