### ISSUE TITLE
Continuous Image Carousel

### ISSUE THREAD

**Issue by kazerniel** [vanokhin/shortcodes-ultimate#112]
**Is your feature request related to a problem? Please describe.**
The Image Carousel (unlike the Slider) quickly reverses back to the first image after the last image. Is there a way to set it to just continue cycling in the same direction instead of the reverse jump?

**Describe the solution you'd like**
Basically how the deprecated Slider behaves, always cycling in the same direction.

**Comment by vanokhin** [comment]
Hi @kazerniel,

I'll add this feature in future updates. Unfortunately, I can't tell you exactly when.
