### ISSUE TITLE
 Image carousel takes images from unpublished posts

### ISSUE THREAD

**Issue by andrixnet** [vanokhin/shortcodes-ultimate#115]
**Describe the bug**
I am trying to create a slider using the "image carousel" shortcode. 
I want to use images from posts (practically to create a carousel representing posts, seeing this shortcode as the only one to fullfill the task).

**To Reproduce**
1. inserty shortcode, image carousel
2. IMages source = recent posts
3. choose whatever settings below
4. click preview

Preview will show featured images from all posts, including unpublished drafts and pending.

**Expected behavior**
I would expect to list featured images from published posts.

**Active plugins (please post a list of active plugins):**
 - blossom themes toolkit
 - classic editor
 - svg support

**System (please complete the following information):**
 - Device: any
 - Browser : Firefox
 - Plugin version 5.9.2
 - PHP version 7.3

**Comment by vanokhin** [comment]
Hi @andrixnet,

please follow the steps below.

1. Add the following snippet to the end of the `functions.php` file:

```php
add_filter( 'su/get_gallery_slides_query', function( $query, $source, $atts ) {

	printf( '<hr>Query:<br>' );
	var_dump( $query );
	printf( '<hr>Source:<br>' );
	var_dump( $source );
	printf( '<hr>Atts:<br>' );
	var_dump( $atts );

	return $query;

}, 10, 3 );
```

2. Insert your shortcode into the editor and also post it here. This is how it should look like:

```
[su_image_carousel source="posts: recent"]
```

3. Save the page and click View Page;
4. Copy the output of the shortcode (or take a screenshot) and post it here. This is how it should look like:

![06-08-2020@14-38-20](https://user-images.githubusercontent.com/1898673/89527756-87e1c880-d7f2-11ea-8bf0-268b669ba350.png)

**Comment by andrixnet** [comment]
```Query:
array(3) { ["post_type"]=> string(3) "any" ["meta_key"]=> string(13) "_thumbnail_id" ["posts_per_page"]=> int(20) } Source:
array(3) { ["type"]=> string(5) "posts" ["tax"]=> string(0) "" ["ids"]=> string(6) "recent" } Atts:
array(21) { ["source"]=> string(13) "posts: recent" ["limit"]=> int(20) ["slides_style"]=> string(5) "photo" ["controls_style"]=> string(4) "dark" ["crop"]=> string(3) "1-1" ["columns"]=> int(1) ["adaptive"]=> string(3) "yes" ["spacing"]=> string(3) "yes" ["align"]=> string(6) "center" ["max_width"]=> string(4) "none" ["captions"]=> string(2) "no" ["arrows"]=> string(3) "yes" ["dots"]=> string(3) "yes" ["link"]=> string(4) "post" ["target"]=> string(5) "blank" ["autoplay"]=> float(5) ["speed"]=> string(6) "medium" ["image_size"]=> string(5) "large" ["outline"]=> string(3) "yes" ["class"]=> string(0) "" ["prefer_caption"]=> string(2) "no" } 
```

This is the output requested, though without the problem.

However during my tests today I was unable to reproduce the problem. 
The shortcode behaved as expected (only drew images from featured image of published posts). 
Shortcodes plugin is at same version, though I might have updated some other component since my report.

Not sure what happened, when I reported it the behaviour was consistent in error, all tests, both in posts and in widgets. Now it works as expected in all tests.

**Comment by andrixnet** [comment]
```Query:
array(3) { ["post_type"]=> string(3) "any" ["meta_key"]=> string(13) "_thumbnail_id" ["posts_per_page"]=> int(20) } Source:
array(3) { ["type"]=> string(5) "posts" ["tax"]=> string(0) "" ["ids"]=> string(6) "recent" } Atts:
array(21) { ["source"]=> string(13) "posts: recent" ["limit"]=> int(20) ["slides_style"]=> string(5) "photo" ["controls_style"]=> string(4) "dark" ["crop"]=> string(3) "1-1" ["columns"]=> int(1) ["adaptive"]=> string(3) "yes" ["spacing"]=> string(3) "yes" ["align"]=> string(6) "center" ["max_width"]=> string(4) "none" ["captions"]=> string(2) "no" ["arrows"]=> string(3) "yes" ["dots"]=> string(3) "yes" ["link"]=> string(4) "post" ["target"]=> string(5) "blank" ["autoplay"]=> float(5) ["speed"]=> string(6) "medium" ["image_size"]=> string(5) "large" ["outline"]=> string(3) "yes" ["class"]=> string(0) "" ["prefer_caption"]=> string(2) "no" } 
```

This is the output requested, though without the problem.

However during my tests today I was unable to reproduce the problem. 
The shortcode behaved as expected (only drew images from featured image of published posts). 
Shortcodes plugin is at same version, though I might have updated some other component since my report.

Not sure what happened, when I reported it the behaviour was consistent in error, all tests, both in posts and in widgets. Now it works as expected in all tests.

**Comment by andrixnet** [comment]
```Query:
array(3) { ["post_type"]=> string(3) "any" ["meta_key"]=> string(13) "_thumbnail_id" ["posts_per_page"]=> int(20) } Source:
array(3) { ["type"]=> string(5) "posts" ["tax"]=> string(0) "" ["ids"]=> string(6) "recent" } Atts:
array(21) { ["source"]=> string(13) "posts: recent" ["limit"]=> int(20) ["slides_style"]=> string(5) "photo" ["controls_style"]=> string(4) "dark" ["crop"]=> string(3) "1-1" ["columns"]=> int(1) ["adaptive"]=> string(3) "yes" ["spacing"]=> string(3) "yes" ["align"]=> string(6) "center" ["max_width"]=> string(4) "none" ["captions"]=> string(2) "no" ["arrows"]=> string(3) "yes" ["dots"]=> string(3) "yes" ["link"]=> string(4) "post" ["target"]=> string(5) "blank" ["autoplay"]=> float(5) ["speed"]=> string(6) "medium" ["image_size"]=> string(5) "large" ["outline"]=> string(3) "yes" ["class"]=> string(0) "" ["prefer_caption"]=> string(2) "no" } 
```

This is the output requested, though without the problem.

However during my tests today I was unable to reproduce the problem. 
The shortcode behaved as expected (only drew images from featured image of published posts). 
Shortcodes plugin is at same version, though I might have updated some other component since my report.

Not sure what happened, when I reported it the behaviour was consistent in error, all tests, both in posts and in widgets. Now it works as expected in all tests.

**Comment by andrixnet** [comment]
```Query:
array(3) { ["post_type"]=> string(3) "any" ["meta_key"]=> string(13) "_thumbnail_id" ["posts_per_page"]=> int(20) } Source:
array(3) { ["type"]=> string(5) "posts" ["tax"]=> string(0) "" ["ids"]=> string(6) "recent" } Atts:
array(21) { ["source"]=> string(13) "posts: recent" ["limit"]=> int(20) ["slides_style"]=> string(5) "photo" ["controls_style"]=> string(4) "dark" ["crop"]=> string(3) "1-1" ["columns"]=> int(1) ["adaptive"]=> string(3) "yes" ["spacing"]=> string(3) "yes" ["align"]=> string(6) "center" ["max_width"]=> string(4) "none" ["captions"]=> string(2) "no" ["arrows"]=> string(3) "yes" ["dots"]=> string(3) "yes" ["link"]=> string(4) "post" ["target"]=> string(5) "blank" ["autoplay"]=> float(5) ["speed"]=> string(6) "medium" ["image_size"]=> string(5) "large" ["outline"]=> string(3) "yes" ["class"]=> string(0) "" ["prefer_caption"]=> string(2) "no" } 
```

This is the output requested, though without the problem.

However during my tests today I was unable to reproduce the problem. 
The shortcode behaved as expected (only drew images from featured image of published posts). 
Shortcodes plugin is at same version, though I might have updated some other component since my report.

Not sure what happened, when I reported it the behaviour was consistent in error, all tests, both in posts and in widgets. Now it works as expected in all tests.

**Comment by vanokhin** [comment]
Well, that could happen if a third-party plugin modifies the `WP_Query`. Probably, you’ve updated that plugin already.

I’m closing the issue. Feel free to open a new one if the problem will come back.
