### ISSUE TITLE
Anchor on su_spoiler within inactive su_tabs not working

### ISSUE THREAD

**Issue by TheBoegl** [vanokhin/shortcodes-ultimate#57]
I have a few tabs which contain spoilers. I can set anchors on the tabs and on the spoilers which are working correctly, i.e. I can select the tab to be opened or expand a spoiler on the initial/first tab but not on another tab.
What I want to archive is the following: I want to link to the second tab and expand a spoiler with a defined anchor.

An example would look like this:
```html
[su_tabs]
  [su_tab title="first tab"]
    Description for first tab.
  [/su_tab]
  [su_tab title="second tab" anchor="tab2"]
    [su_spoiler title="first spoiler" style="fancy" anchor="tab2spoiler1"]
      Description for first spoiler in second tab.
    [/su_spoiler]
    [su_spoiler title="second spoiler" style="fancy" anchor="tab2spoiler2"]
      Description for second spoiler in second tab.
    [/su_spoiler]
  [/su_tab]
[/su_tabs]
```
I would like to provide a link like `/myTest/#tab2spoiler2` to select `tab2` and expand my second spoiler.

Is this possible right now or is this a bug/not intended that way?

**Comment by vanokhin** [comment]
Hi,

this isn't a feature and it won't be added, sorry.

Please read my comments [here](https://wordpress.org/support/topic/unable-to-navigate-to-cross-tab-anchors-in-su_tabs/).
