### ISSUE TITLE
Edit used shortcode

### ISSUE THREAD

**Issue by koreos** [vanokhin/shortcodes-ultimate#93]
Hi, how can edit content and settings of used shortcode in editor?

Is edit allow when I will buy add-ons?

**Comment by vanokhin** [comment]
Hi @koreos,

there is no way to edit shortcodes except manually.

None of the premium add-ons will change that.

**Comment by koreos** [comment]
Very bad.

**Comment by koreos** [comment]
That is ok for few things. But if you have a lot of is big problem, it waste your time! Then much better is something like this https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/ to quick edit.
