### ISSUE TITLE
Add support for www.youtube-nocookie.com

### ISSUE THREAD

**Issue by ashucg** [vanokhin/shortcodes-ultimate#94]
Please consider adding support for www.youtube-nocookie.com domain as some users, such as myself, prefer using it over www.youtube.com

**Comment by vanokhin** [comment]
Hi @ashucg,

the `youtube-nocookie.com` domain is already supported by both `[su_youtube]` and `[su_youtube_advanced]` shortcodes.

**Comment by ashucg** [comment]
@vanokhin ah, yeah, sorry, it didn't work when I used it, must be something else.
