### ISSUE TITLE
Slider Swiper JS Collision: Upgrading to Swiper V4

### ISSUE THREAD

**Issue by SirLouen** [vanokhin/shortcodes-ultimate#95]
I posted about a collision between Elementor and Shortcodes Ultimate. All the explanation can be found here:
https://wordpress.org/support/topic/slider-swiper-js-collision/

I've started this dev thread in order to see if this plugin can update to the latest Swiper API so it will automatically merge compatibility with Elementor (at least for this slider/carrousel shortcode feature)

After some research I've found that the latest Swiper V4 API includes some new properties for the object. Tried updating galleries-shortcodes.js with the new implementation. But it just doesn't work out of the box with the simple tweaks adaptations to the new API:

```
// Enable sliders
	$('.su-slider').each(function () {
	  // Prepare data
	  var $slider = $(this);
	  // Apply Swiper
	  var $swiper = new Swiper($slider,{
	    wrapperClass: 'su-slider-slides',
	    slideClass: 'su-slider-slide',
	    slideActiveClass: 'su-slider-slide-active',
	    slideVisibleClass: 'su-slider-slide-visible',
	    pagination: {
			 	el: '.su-slider-pagination',
	      clickable: true,
	    },
	    autoplay: {
				delay: $slider.data('autoplay'),
			},
	    grabCursor: true,
	    direction: 'horizontal',
	    mousewheel: $slider.data('mousewheel'),
	    speed: $slider.data('speed'),
	    autoHeight: $slider.hasClass('su-slider-responsive-yes'),
	    loop: true,
			navigation: {
	 			nextEl: '.su-slider-prev',
	 			prevEl: '.su-slider-next',
			},
	  });
	  // Prev button
	  $slider.find('.su-slider-prev').click(function (e) {
	         $swiper.slidePrev();
	  });
	  // Next button
	  $slider.find('.su-slider-next').click(function (e) {
	         $swiper.slideNext();
	  });
});
```

**Comment by FlyThePlanet** [comment]
I have the same problem. I hope it will be fixed soon.

**Comment by vanokhin** [comment]
I made a new, better, shortcode, called [Image Carousel](https://getshortcodes.com/docs/image-carousel/). It can create both sliders and carousels. Please use it instead of the old shortcodes.

You can even [replace old shortcodes](https://getshortcodes.com/docs/replace-slider-and-carousel-with-image-carousel/) (inserted previously) with the new one.

Old shortcodes will not be updated anymore, as it requires too much work.

**Comment by FlyThePlanet** [comment]
> I made a new, better, shortcode, called Image Carousel.

Yes I realized this soon after I posted my comment above.
But... there's some major differences in between the 2 shortcodes and the new one is not necessarily better in all aspects.

I'll identify the most problematic differences and will submit an enhancement ticket.
