### ISSUE TITLE
$carousel.swiper is not a function

### ISSUE THREAD

**Issue by qq781548819** [vanokhin/shortcodes-ultimate#96]
**Describe the bug**

**To Reproduce**
1. Go to 'edit post'
2. Click on 'insert carousel'
3. See error
```
[su_carousel source="media: 10,11" limit="2" link="lightbox" width="640" height="400" items="1" title="no"]
```
![](http://ww1.sinaimg.cn/large/e65777e7gy1g48rq9ufunj20yp0f2ae1.jpg)

**Comment by qq781548819** [comment]
Thanks to the author for looking at this problem

**Comment by qq781548819** [comment]
The cause was found and was in conflict with an elementor plug-in,But I'm not going to solve this problem

**Comment by vanokhin** [comment]
Hi @qq781548819 ,

the Swiper library will be replaced with another lib in the closest update (a couple of months).

Thank you for the report.
