### ISSUE TITLE
Add user_first_name, user_last_name, user_nickname, user_avatar_url fields to the User shortcode

### ISSUE THREAD

**Issue by FlyThePlanet** [vanokhin/shortcodes-ultimate#99]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when when it comes to message personalization.
In many languages we just use the First name. Like "Hi John,".
In other cases, we may want to be more formal and use only the last name. Like "Dear Mr Smith,"
But with the current fields available, we can't do it. No field available with User shortcode allows to do it, not even "Display name" as everyone can choose whatever they want to display.

So as First name and Last name are core WordPress fields, please add those 2 fields to the User shortcode. And weather they are fill in or not should not prevent from adding them. On some websites those fields are mandatory so it's not an issue.

Same for user_nickname. It's a core WP field, on some websites it's mandatory and the admin may want to communicate only using nicknames to respect the anonymity.

At last, I also need to complete the personalization by adding the user Avatar. But I need the url for that and it's also not provided by the User shortcode. So please add the user_avatar_url field.

Thanks very much!
It should be easy improvements.

**Describe the solution you'd like**
Add 4 fields to the User shortcode:
- user_first_name,
- user_last_name,
- user_nickname,
- user_avatar_url

**Describe alternatives you've considered**
Use another plugin like User Shortcodes Plus that provides everything for free but it would be a pity to use another plugin just for that.

**Additional context**

**Comment by vanokhin** [comment]
Hi @FlyThePlanet,

Thank you for the suggestion, I like the idea. I'll see what I can do. Probably, I'll add it in the closest update, but I'm unsure now.

**Comment by vanokhin** [comment]
Since version 5.7.0 use the following shortcodes:

```
[su_user field="first_name"]

[su_user field="last_name"]

[su_user field="nickname"]
```

Avatar URL isn't stored in the DB, so it can't be retrieved with the `[su_user]` shortcode. Maybe I'll add a separate shortcode in the future.

**Comment by FlyThePlanet** [comment]
Hi,

> Since version 5.7.0 use the following shortcodes...

Thanks @vanokhin ! 👍 

But on the changelog you wrote...

> The [su_user] shortcode can now display user meta

https://fr.wordpress.org/plugins/shortcodes-ultimate/#developers

And the user shortcode documentation has not been updated...
https://getshortcodes.com/docs/user-data/

So quick question: have you just added "first_name", "last_name" and "nickname" parameters OR the possibility to use any "meta_key" of the "wp_usermeta" table?

**Comment by vanokhin** [comment]
Hi @FlyThePlanet,

you can use almost any meta field name from `wp_usermeta`. The only limitation, the value must be a string. Serialized arrays, like in `session_tokens`, won't work.

**Comment by FlyThePlanet** [comment]
Ok thanks! 👍

**Comment by vanokhin** [comment]
Oh, and I updated the docs. Thanks for the reminder :)
